# Generated by Django 3.2.25 on 2024-07-28 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='users',
            new_name='Member',
        ),
    ]
